controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    Magia_verde = sprites.createProjectileFromSprite(assets.image`Magia verde`, Hechicera, 0, -100)
    Magia_verde.setStayInScreen(false)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Hechicera.vy = -120
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    Bola_de_fuego.destroy(effects.warmRadial, 100)
    Magia_verde.destroy()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    Bola_de_fuego.destroy(effects.fire, 100)
    info.changeLifeBy(-1)
})
let Bola_de_fuego: Sprite = null
let Magia_verde: Sprite = null
let Hechicera: Sprite = null
tiles.setTilemap(tilemap`level1`)
Hechicera = sprites.create(assets.image`M_Atras`, SpriteKind.Player)
Hechicera.setStayInScreen(false)
info.setLife(3)
Hechicera.ay = 200
controller.moveSprite(Hechicera, 150, 0)
scene.setBackgroundImage(img`
    ccccccccccccccbbbbbbbbbccccccccccccccccbbbbbbbbbbbccccccccccccccccbbbbccccccccccccbbbbbbbbccccccccccccccbbbbccccccccccccccccccccccbbbbbbcccccccccccccccccccccbbb
    ccccccccccccccbbbbbbbbbccccccccccccccccbbbbbbbbbbbccccccccccccccccbbbbccccccccccccbbbbbbbbccccccccccccccccccccccccccccccccccccccccbbbbbbcccccccccccccccccccccbbb
    ccccccccccccccbbbbbbbbbccccccccccccccccbbbbbbbbbbbccccccccccccccccbbbbccccccccccccbbbbbbbbccccccccccccccccccccccccccccccccccccccccbbbbbbcccccccccccccccccccccbbb
    ccccccccccccccbbbbbbbbbcccccccccccccccbbbbbbbbbbbbcccccbbbbbbbbbbbbbbbccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccbbbbbbcccccccccccccccccccccbbb
    ccccccccccccccbbbbbbbbbbccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccbbbbbbbbbbbccccccccbbbbbbbbcccccbbb
    ccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccfffffffffffffffffffffffffffffffffffffbbccccccbbb
    ccccccccccbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbccccccbbb
    cccccccccbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbccccccbbb
    cccccccccbbbfffffffffffffffeefeeeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbccccccbbb
    cccccccbbbbbffffffffeeeeeeeeefeeeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeeffffffffbbcccccbbbb
    cccccccbbbbbfffffffeeeefeeeeefeeefeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeeeeeefeffffffbccccccbbbb
    cccccccccbbbffffffeeeeefeeeeefeeefeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeefeeeeeefeefffffbccccccbbbb
    ccccccccccccffffffeeeeefeeeeefeeefeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeeefeeeeeefeeeffffbccccccbbbb
    ccccccccccccfffffeeeeeefeeeeefeeefeeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeeeefeeeeeefeeeffffbccccccccbb
    ccccccccccccfffffeeeeeefeeeeefeeefeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeeeeefeeeeeefeeeefffbccccccccbb
    ccccccccccccfffefeeeeeefeeeeefeeefeeeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeeeeefeeeeeefeeeeeffbccccccccbb
    ccccccccccccffeefeeeeeefeeeeefeeefeeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeefeeeeefeeeeeefeeeeeffbccccccccbb
    cccccccbbbbbffeefeeeeeefeeeeefeeefeeeefefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeefeeeeefeeeeeefeeeeeefbccccccccbb
    cccccbbbbbbbfeeefeeeeeefeeeeefeeefeeeefeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeefeeeeefeeeeeefeeeeeefbccccccccbb
    ccccccccbbbbeeeefeeeeeefeeeeefeeefeeeefeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeefeeeeefeeeeeefeeeeeeebbccccccbbb
    cccccccccbbbeeeefeeeeeefeeeeefeeefeeeefeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeeeefeeeeefeeeeeefeeeeeeebbccccccbbb
    cccccccccbbbeeeefeeeeeefeeeeefeeefeeeefeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeefeeeefeeeeefeeeeeefeeeeeeeebccccccbbb
    cccccccccbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeefeeeefeeeeefeeeeeefeeeeeeeebccccccbbb
    cccccccccbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeefeeeefeeeeefeeeeeefeeeeeeeebccccccbbb
    ffffcccccbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    ffffbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    bbbbbccccccceeeefeeeeeefeeeeefeeefeeeefeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    bbbbbccccccceeeefeeeeeefeeeeefeeefeeeefeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    bbbbbccccccceeeefeeeeeefeeeeefeeefeeeefeeeffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    bbbbbccccccceeeefeeeeeefeeeeefeeefeeeefeeeffffffffffffffffffffffffffffbfffffbfffffffffffffffffffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    bbbbbccccccceeeefeeeeeefeeeeefeeefeeeefeeefffffffffffffffffffffffffffbbffffbbfffffffffbbbfffffffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    bbbbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffffffffffffffbfffffffbbffffbffffffffffbbbfffffffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    ccccccccbbbbeeeefeeeeeefeeeeefeeefeeeefeeeffffffffffffffffffbbfffffbbbbfffbbfffffffffbbbbbffffffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    ccccccccbbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffffffffffffbbbbbfffbbbbbbbbbfffffffffbbbbbfffffffffffbffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    ccccccccbbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffffffbffffbbbbbbbbbbbbbbbbbbfffffffffbbbbbfffbffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    ccccccccbbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffbfffbbbbbbbbbbbbbbbbbbbbbbbfffbbffffbbbbbfffbffffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    ccccccccbbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffbfffbbbbbbbbbbbbbbbbbbbbbbbfffbbfffbbbbbbbbbbbfffffffffffffffffffffffffeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    bbbbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffbfffbbbbbbbbbbbbbbbbbbbbbbbfffbbfffbbbbbbbbbbbfffbfffffffffffffffffffbfeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    ccccbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffbfffbbbbbbbbbbbbbbbbbbbbbbbfffbffffbbbbbbbbbbbbbbbfffffffffbbffffffffbfeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    ccccccbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffbbbbbbbbbbbbbbbfffffffffbbffffffffbfeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    ccccccbfffffeeeefeeeeeefeeeeefeeefeeeefeeeffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffbbbbbbbbbbbbbbbbbfffffbbbbbffffbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccccb
    ccccccbfbbbbeeeefeeeeeefeeeeefeeefeeeefeeeffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffbbbbbbbbbbbbbbbbbfffffbbbbbbfffbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccccb
    ccccccbfbbbbeeeefeeeeeefeeeeefeeefeeeefeeeffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffbbbbbbbbbbbbbbbbbfffffbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebbcccccccb
    ccccccbfbbbbeeeefeeeeeefeeeeefeeefeeeefeeefbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffbbbbbbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccccb
    cccffffffffbeeeefeeeeeefeeeeefeeefeeeefeeefbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffbbbbbbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccccb
    cccbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccccb
    cccbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccccb
    cccbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    bfffffffffbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    bbbbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccbbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccbbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccbbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccccb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccccb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccccb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebbcccccccb
    cccbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccccb
    cccfffbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccccb
    ccccccccccbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeeccccccccbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    cccbbbbbcccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    bbbbbbbbccbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccbbb
    bbfbbbbbffbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    bbfbbbbbbfbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    bbfbbbbbbfbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    bbffffffffbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    bbbbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebcccccccbb
    cccccbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccccb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccccb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccccb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeefffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeebccccccccb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeeffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeefeeeefeeeeefeeeeeefeeeeeeeecccccccccb
    cccccccccccbeeeefeeeeeefeeeeefeeefeeeefeeefffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffeeefeeeefeeeeefeeeeeefeeeeeeeecccccccccb
    cccbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeefeeefffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffeeefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    cccffffffffbeeeefeeeeeefeeeeefeeefeeeeeeeeffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffefeeeefeeeeefeeeeeefeeeeeeeecccccccbbb
    cccbbbbbbbbbeeeefeeeeeefeeeeefeeefeeeeeeffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffeeeefeeeeefeeeeeefeeeeeeeecccccccccc
    ccccccccccbbeeeefeeeeeefeeeeefeeefeeeefffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffefeeeeefeeeeeefeeeeeeeecccccccccc
    ccccccccccbbeeeefeeeeeefeeeeefeeefefffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffeeeeefeeeeeefeeeeeeeecccccccccc
    ccccccccccbbeeeefeeeeeefeeeeefeeefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeefeeeeeefeeeeeeeecccccccccc
    ccccccccccbbeeeefeeeeeefeeeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeeeefeeeeeeeecccccccccc
    ccccccccccbbeeeefeeeeeefeeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeeefeeeeeeeecccccccccc
    ccccccccccbbeeeefeeeeeefeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeefeeeeeeeecccccccccb
    ccccccccccbbeeeefeeeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeeeeeecccccccccb
    ccccccccccbbeeeefeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeeeecccccccccb
    ccccccccccbbeeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeecccccccccb
    bbbbbbbbbbbbfeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbcccccccb
    fffffffffffbfeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfbbbcccccccc
    bbbbbbbbbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfbbbbccccccc
    cccccbfbbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf77bbccccccc
    cccccbfbbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf77bbbcccccc
    cccccbfbbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf77bcccccccc
    cccccbbbbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf77bcccccccc
    cccccbb77777fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf77bcccccccc
    cccccbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7bcccccccc
    cccccbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf7bcccccccc
    cccccbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf7bcccccccc
    cccbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf7bbbcccccc
    cccbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf777bcccccc
    cccb777fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf777bcccccc
    cccb777fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf777bcccccc
    cccbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbcccccc
    bbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfbcccccc
    bbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf777cccc
    7777fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf777cccc
    7777fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf777cccc
    7777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    `)
game.onUpdateInterval(1000, function () {
    Bola_de_fuego = sprites.create(assets.image`Bola de fuego`, SpriteKind.Enemy)
    Bola_de_fuego.setVelocity(0, 100)
    Bola_de_fuego.setPosition(randint(12, 150), 0)
    Bola_de_fuego.setStayInScreen(false)
})
